spring:
  kafka:
    bootstrap-servers: ${BPM_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${BPM_CORE_BASE_GROUP_ID:BPM_CORE}
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
    producer:
      batch-size: 65536
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      ack-mode: manual_immediate